### PR TITLE
Code homepage - clean code - fix bug

### PR DESCRIPTION
**Pull request by deveyy**
- Continues code homepage
- Clean code and delete component don't used
- fix some bug basic 
- set props api static
------------Feauture--------------------
- Code Typing in carousel in homepage 🎇🎇
- Code finish homepage 🎇🎇

### CODE REVIEW

**Review by ddthien-coder — COMMENTED** [review]
- Continues code homepage
- Clean code and delete component don't used
- fix some bug basic 
- set props api static
------------Feauture--------------------
- Code Typing in carousel in homepage 🎇🎇
- Code finish homepage 🎇🎇

**Comment by deveyy** [comment]
> * Continues code homepage
> * Clean code and delete component don't used
> * fix some bug basic
> * set props api static
>   ------------Feauture--------------------
> * Code Typing in carousel in homepage 🎇🎇
> * Code finish homepage 🎇🎇

--> Approval 👍👌

**Review by ddthien-coder — APPROVED** [review]
- Continues code homepage
- Clean code and delete component don't used
- fix some bug basic 
- set props api static
------------Feauture--------------------
- Code Typing in carousel in homepage 🎇🎇
- Code finish homepage 🎇🎇

**Review by ddthien-coder — COMMENTED** [review]
Fix conflict

**Review by deveyy — COMMENTED** [review]
fix conflict

**Comment by deveyy** [comment]
> Fix conflict

fixing

**Comment by ddthien-coder** [comment]
> > Fix conflict
> 
> fixing

done -> Approval

**Pull request merged**
