### PR TITLE
update homepage & fix bug

### PR DESCRIPTION
**Pull request by deveyy**

### CODE REVIEW

**Review by ddthien-coder — COMMENTED** [review]
Clean code
update project
update home
fix bug

**Comment by ddthien-coder** [comment]
> _ No description provided. _

Clean code
update project
update home
fix bug

**Comment by deveyy** [comment]
> > _ No description provided. _
> 
> Clean code update project update home fix bug

-> Deploy github.io

**Review by ddthien-coder — APPROVED** [review]
Clean code
update project
update home
fix bug
deploy github.io

**Pull request merged**
